### ISSUE TITLE
Why not enhance the msg ?

### ISSUE THREAD

**Issue by dceejay** [dotnsf/node-red-contrib-dotnsf-mynode#1]
Rather than replace msg.payload would it not be more useful to add msg.hash and return both the hash and the original payload ? As more often you would want both in the next stage of processing.

**Comment by dotnsf** [comment]
@dceejay It sounds nice idea! I will try to do that in next update. Thanks.

**Comment by dotnsf** [comment]
fixed in v0.0.3

**Comment by dceejay** [comment]
Hi

that's not what I meant :-) .... 

I meant leave the `msg.payload` as `msg.payload` and just add `msg.hash` with the hash in.
so the code would be

     var payload = msg.payload;
      hash.update( payload );
      msg.hash = hash.digest( 'hex' );
      node.send( msg );

Or indeed if you wanted to return the hash as payload (as per your version 1 then move msg.payload to msg.originalpayload  and put the hash on msg.payload ... either would be fine (as long as the info panel says what happens :-)

**Comment by dotnsf** [comment]
@dceejay Thanks for making me understand what you meant. I have fixed it again in v0.0.4.

**Comment by dceejay** [comment]
Thanks for the node !
