### ISSUE TITLE
"Error: Digest already called"

### ISSUE THREAD

**Issue by sergekeyser** [dotnsf/node-red-contrib-dotnsf-mynode#4]
@dotnsf I am using your node, thanks very much for making this.

Unfortunately after I run it once (does get hash that one time) it mentions "Error: Digest already called"
Any idea what I am doing wrong?

Cheers,

Serge

**Comment by dotnsf** [comment]
Hello Serge. I am happy to hear your feedback.

I have fixed my code in v0.1.2. I believe now this error would not be shown again. Thanks.
